[platformio]
default_envs = sim
src_dir = ..
include_dir = ../include

[env:sim]
platform = native
build_type = debug
lib_deps =
  M5GFX@0.2.19
  M5Unified@0.2.13
  lvgl/lvgl@9.4.0
  https://github.com/gkoh/TinyGPSPlus#92ac8c2
lib_extra_dirs =
  ../../../../.pio/libdeps/m5stick-s3
build_src_filter =
  +<sim/*.cpp>
  +<src/FurbleCalibrate.cpp>
  +<src/FurbleGPS.cpp>
  +<src/FurbleSettings.cpp>
  +<src/FurbleSpinValue.cpp>
  +<src/FurbleUI.cpp>
  +<src/FurbleUIIntervalometer.cpp>
  +<components/icons/*.c>
build_flags =
  -O0
  -std=c++17
  -Wall
  -Wextra
  -Wno-unused-parameter
  -D_THREAD_SAFE
  -DFURBLE_M5STICKS3
  -DFURBLE_SIM
  -DFURBLE_VERSION=\"sim\"
  -DFURBLE_TEST_VERSION=1
  -DFURBLE_BATTERY_DEBUG=0
  -DM5GFX_SCALE=2
  -DLV_CONF_INCLUDE_SIMPLE
  -DLV_LVGL_H_INCLUDE_SIMPLE
  -DLV_KCONFIG_IGNORE
  -I${PROJECT_DIR}
  -I${PROJECT_DIR}/shim
  -I${PROJECT_DIR}/../components/icons
  -I${PROJECT_DIR}/../lib/preferences
  -I${PROJECT_DIR}/../lib/furble
  -I/usr/local/include/SDL2
  -L/usr/local/lib
  -I${sysenv.HOMEBREW_PREFIX}/include/SDL2
  -L${sysenv.HOMEBREW_PREFIX}/lib
  -lSDL2
