#!/usr/bin/env python3
"""Generate a small LVGL config from an ESP-IDF sdkconfig file."""

from __future__ import annotations

import argparse
from pathlib import Path


CHOICE_DEFINES = {
    "CONFIG_LV_USE_BUILTIN_MALLOC": ("LV_USE_STDLIB_MALLOC", "LV_STDLIB_BUILTIN"),
    "CONFIG_LV_USE_CLIB_MALLOC": ("LV_USE_STDLIB_MALLOC", "LV_STDLIB_CLIB"),
    "CONFIG_LV_USE_MICROPYTHON_MALLOC": (
        "LV_USE_STDLIB_MALLOC",
        "LV_STDLIB_MICROPYTHON",
    ),
    "CONFIG_LV_USE_RTTHREAD_MALLOC": ("LV_USE_STDLIB_MALLOC", "LV_STDLIB_RTTHREAD"),
    "CONFIG_LV_USE_CUSTOM_MALLOC": ("LV_USE_STDLIB_MALLOC", "LV_STDLIB_CUSTOM"),
    "CONFIG_LV_USE_BUILTIN_STRING": ("LV_USE_STDLIB_STRING", "LV_STDLIB_BUILTIN"),
    "CONFIG_LV_USE_CLIB_STRING": ("LV_USE_STDLIB_STRING", "LV_STDLIB_CLIB"),
    "CONFIG_LV_USE_MICROPYTHON_STRING": (
        "LV_USE_STDLIB_STRING",
        "LV_STDLIB_MICROPYTHON",
    ),
    "CONFIG_LV_USE_RTTHREAD_STRING": ("LV_USE_STDLIB_STRING", "LV_STDLIB_RTTHREAD"),
    "CONFIG_LV_USE_CUSTOM_STRING": ("LV_USE_STDLIB_STRING", "LV_STDLIB_CUSTOM"),
    "CONFIG_LV_USE_BUILTIN_SPRINTF": ("LV_USE_STDLIB_SPRINTF", "LV_STDLIB_BUILTIN"),
    "CONFIG_LV_USE_CLIB_SPRINTF": ("LV_USE_STDLIB_SPRINTF", "LV_STDLIB_CLIB"),
    "CONFIG_LV_USE_MICROPYTHON_SPRINTF": (
        "LV_USE_STDLIB_SPRINTF",
        "LV_STDLIB_MICROPYTHON",
    ),
    "CONFIG_LV_USE_RTTHREAD_SPRINTF": ("LV_USE_STDLIB_SPRINTF", "LV_STDLIB_RTTHREAD"),
    "CONFIG_LV_USE_CUSTOM_SPRINTF": ("LV_USE_STDLIB_SPRINTF", "LV_STDLIB_CUSTOM"),
    "CONFIG_LV_OS_NONE": ("LV_USE_OS", "LV_OS_NONE"),
    "CONFIG_LV_OS_PTHREAD": ("LV_USE_OS", "LV_OS_PTHREAD"),
    "CONFIG_LV_OS_FREERTOS": ("LV_USE_OS", "LV_OS_FREERTOS"),
    "CONFIG_LV_OS_CMSIS_RTOS2": ("LV_USE_OS", "LV_OS_CMSIS_RTOS2"),
    "CONFIG_LV_OS_RTTHREAD": ("LV_USE_OS", "LV_OS_RTTHREAD"),
    "CONFIG_LV_OS_WINDOWS": ("LV_USE_OS", "LV_OS_WINDOWS"),
    "CONFIG_LV_OS_MQX": ("LV_USE_OS", "LV_OS_MQX"),
    "CONFIG_LV_OS_SDL2": ("LV_USE_OS", "LV_OS_SDL2"),
    "CONFIG_LV_OS_CUSTOM": ("LV_USE_OS", "LV_OS_CUSTOM"),
    "CONFIG_LV_TXT_ENC_UTF8": ("LV_TXT_ENC", "LV_TXT_ENC_UTF8"),
    "CONFIG_LV_TXT_ENC_ASCII": ("LV_TXT_ENC", "LV_TXT_ENC_ASCII"),
}

SKIP_CONFIGS = {
    "CONFIG_LV_CONF_SKIP",
    "CONFIG_LV_CONF_MINIMAL",
    "CONFIG_LV_COLOR_DEPTH_1",
    "CONFIG_LV_COLOR_DEPTH_8",
    "CONFIG_LV_COLOR_DEPTH_16",
    "CONFIG_LV_COLOR_DEPTH_24",
    "CONFIG_LV_COLOR_DEPTH_32",
    "CONFIG_LV_DRAW_SW_ASM_NONE",
    "CONFIG_LV_DRAW_SW_ASM_NEON",
    "CONFIG_LV_DRAW_SW_ASM_HELIUM",
    "CONFIG_LV_DRAW_SW_ASM_CUSTOM",
    "CONFIG_LV_TXT_ENC_UTF8",
    "CONFIG_LV_TXT_ENC_ASCII",
}


def convert_value(value: str) -> str:
    if value == "y":
        return "1"
    if value == "n":
        return "0"
    return value


def generate(source: Path, destination: Path) -> None:
    lines = [
        "/* Generated by tools/gen_lv_conf.py. Do not edit by hand. */",
        "#ifndef LV_CONF_H",
        "#define LV_CONF_H",
        "",
    ]

    for raw_line in source.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if line.startswith("CONFIG_LV_") and "=" in line:
            name, value = line.split("=", 1)
            if value == "y" and name in CHOICE_DEFINES:
                output_name, output_value = CHOICE_DEFINES[name]
                lines.append(f"#define {output_name} {output_value}")
            elif value == "y" and name.startswith("CONFIG_LV_FONT_DEFAULT_"):
                font_name = name.removeprefix("CONFIG_LV_FONT_DEFAULT_").lower()
                lines.append(f"#define LV_FONT_DEFAULT &lv_font_{font_name}")
            elif name in SKIP_CONFIGS or name in CHOICE_DEFINES:
                continue
            else:
                lines.append(f"#define {name[7:]} {convert_value(value)}")
        elif line.startswith("# CONFIG_LV_") and line.endswith(" is not set"):
            name = line[2 : line.index(" is not set")]
            if name not in SKIP_CONFIGS and name not in CHOICE_DEFINES:
                lines.append(f"#define {name[7:]} 0")

    lines.extend(["", "#endif"])
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("sdkconfig", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.sdkconfig, args.output)


if __name__ == "__main__":
    main()
